### ISSUE TITLE
Failed to resolve YANG path: ebgp-multihop/maximum-hop-count

### ISSUE THREAD

**Issue by summed** [CiscoDevNet/terraform-provider-iosxr#212]
am getting 

> panic: Failed to resolve YANG path: ebgp-multihop/maximum-hop-count, element: ebgp-multihop

when trying to add 

``` yaml
  - yang_name: ebgp-multihop/maximum-hop-count
    example: 255
  - yang_name: ebgp-multihop/mpls
    example: true
```

to

> terraform-provider-iosxr/gen/definitions/router_bgp_neighbor_address_family.yaml

 Any idea why that might be?
